# Knife4j接口文档
knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: 123456
  openapi:
    title: 在线文档
    description: "API文档"
    concat: zhengqingya
    email: zhengqingya@it.com
    url: http://gitee.com/zhengqingya
    version: v1.0.0
    license: MIT
    group:
      demo:
        group-name: demo
        api-rule: package
        api-rule-resources:
          - com.zhengqing.demo
