/*
 * This file is generated by jOOQ.
 */
package com.zhengqing.demo.dsl.jooq;


import com.zhengqing.demo.dsl.jooq.tables.TUser;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooq extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq</code>
     */
    public static final Jooq JOOQ = new Jooq();

    /**
     * 用户表
     */
    public final TUser T_USER = TUser.T_USER;

    /**
     * No further instances allowed
     */
    private Jooq() {
        super("jooq", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            TUser.T_USER);
    }
}
