/*
 * This file is generated by jOOQ.
 */
package com.zhengqing.demo.dsl.jooq;


import com.zhengqing.demo.dsl.jooq.tables.TUser;
import com.zhengqing.demo.dsl.jooq.tables.records.TUserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * jooq.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TUserRecord> KEY_T_USER_PRIMARY = Internal.createUniqueKey(TUser.T_USER, DSL.name("KEY_t_user_PRIMARY"), new TableField[] { TUser.T_USER.ID }, true);
}
