/*
 * This file is generated by jOOQ.
 */
package com.zhengqing.demo.dsl.jooq;


import com.zhengqing.demo.dsl.jooq.tables.TUser;


/**
 * Convenience access to all tables in jooq.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户表
     */
    public static final TUser T_USER = TUser.T_USER;
}
