/*
 * This file is generated by jOOQ.
 */
package com.zhengqing.demo.dsl.jooq.tables.pojos;


import java.io.Serializable;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  username;
    private String  nickname;

    public TUser() {}

    public TUser(TUser value) {
        this.id = value.id;
        this.username = value.username;
        this.nickname = value.nickname;
    }

    public TUser(
        Integer id,
        String  username,
        String  nickname
    ) {
        this.id = id;
        this.username = username;
        this.nickname = nickname;
    }

    /**
     * Getter for <code>jooq.t_user.id</code>. 主键ID
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>jooq.t_user.id</code>. 主键ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>jooq.t_user.username</code>. 账号
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>jooq.t_user.username</code>. 账号
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>jooq.t_user.nickname</code>. 昵称
     */
    public String getNickname() {
        return this.nickname;
    }

    /**
     * Setter for <code>jooq.t_user.nickname</code>. 昵称
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUser (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(nickname);

        sb.append(")");
        return sb.toString();
    }
}
